### ISSUE TITLE
typeerror: mean received an invalid combination of arguments - got ()

### ISSUE THREAD

**Issue by qijiezhao** [yjxiong/tsn-pytorch#10]
Hi, I met trouble when running the train script:
`python main.py ucf101 RGB ../TSN/data/ucf101_rgb_train_split_1.txt ../TSN/data/ucf101_rgb_val_split_1.txt --arch BNInception --num_segments 3 --gd 20 --lr 0.001 --lr_steps 30 60 --epochs 80 -b 128 -j 8 --snapshot_pref ucf101_bninception --b 128`

however, an error appears as follows:(including the output of code info)

Initializing TSN with base model: BNInception.
TSN Configurations:
    input_modality:     RGB
    num_segments:       3
    new_length:         1
    consensus_module:   avg
    dropout_ratio:      0.5
        
group: first_conv_weight has 1 params, lr_mult: 1, decay_mult: 1
group: first_conv_bias has 1 params, lr_mult: 2, decay_mult: 0
group: normal_weight has 69 params, lr_mult: 1, decay_mult: 1
group: normal_bias has 69 params, lr_mult: 2, decay_mult: 0
group: BN scale/shift has 2 params, lr_mult: 1, decay_mult: 0
Freezing BatchNorm2D except the first one.
Traceback (most recent call last):
  File "main.py", line 301, in <module>
    main()
  File "main.py", line 124, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "main.py", line 166, in train
    output = model(input_var)
  File "/opt/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 61, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/opt/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 71, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs)
  File "/opt/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/parallel_apply.py", line 46, in parallel_apply
    raise output
TypeError: mean received an invalid combination of arguments - got (dim=int, keepdim=bool, ), but expected one of:
 * no arguments
 * (int dim)

where is the bug?

**Comment by yjxiong** [comment]
Update your pytorch version maybe

**Comment by yjxiong** [comment]
@qijiezhao Any progress?

**Comment by qijiezhao** [comment]
solved!   Feel sorry that I didn't reply this earlier.
