### ISSUE TITLE
fusion

### ISSUE THREAD

**Issue by nationalflag** [yjxiong/tsn-pytorch#11]
Spatial network and temporal network are trained separatly? The fusion of the networks are implemented just in testing stage?

**Comment by yjxiong** [comment]
1. Yes.
2. Yes.

Please read the paper for these details.

**Comment by nationalflag** [comment]
Thanks for you patience! I'll read the paper more carefully.

**Comment by yjxiong** [comment]
Closing this. Please feel free to reopen it if you meet any further problem.
