### ISSUE TITLE
what is the command of RGB and Flow modality fusion?

### ISSUE THREAD

**Issue by chenxlin222** [yjxiong/tsn-pytorch#117]
when we get the scores of rgb stream in rgb.npz and flow stream in flow.npz, how can we get the fusion result with weights of 1:1.5 ?
Thank you very much!

**Comment by chenxlin222** [comment]
For example:
1. we can get the rgb result from the command "python test_models.py ucf101 RGB <ucf101_rgb_val_list> ucf101_bninception_rgb_checkpoint.pth  --arch BNInception --save_scores <score_file_name>"
2. Or we can get the flow result from the command "python test_models.py ucf101 Flow <ucf101_rgb_val_list> ucf101_bninception_flow_checkpoint.pth  --arch BNInception --save_scores <score_file_name> --flow_pref flow_  "
3. but how can we fuse these two results?

**Comment by Mkarami3** [comment]
Hello chenxlin222,
Did you find the answer to your question? Can you please kindly share it with me?
Thank you
