### ISSUE TITLE
dataloader runtime errors

### ISSUE THREAD

**Issue by ntuyt** [yjxiong/tsn-pytorch#17]
python main.py ucf101 RGB ucf101_trainlist01new.txt ucf101_testlist01new.txt  --gpus 1 --arch BNInception --num_segments 3 --gd 20 --lr 0.001 --lr_steps 30 60 --epochs 80  -b 128 -j 8 --dropout 0.8

Initializing TSN with base model: BNInception.
TSN Configurations:
    input_modality:     RGB
    num_segments:       3
    new_length:         1
    consensus_module:   avg
    dropout_ratio:      0.8
        
/home/ytan/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py:360: UserWarning: src is not broadcastable to dst, but they have the same number of elements.  Falling back to deprecated pointwise behavior.
  own_state[name].copy_(param)
group: first_conv_weight has 1 params, lr_mult: 1, decay_mult: 1
group: first_conv_bias has 1 params, lr_mult: 2, decay_mult: 0
group: normal_weight has 69 params, lr_mult: 1, decay_mult: 1
group: normal_bias has 69 params, lr_mult: 2, decay_mult: 0
group: BN scale/shift has 2 params, lr_mult: 1, decay_mult: 0
Freezing BatchNorm2D except the first one.
Traceback (most recent call last):
  File "main.py", line 301, in <module>
    main()
  File "main.py", line 124, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "main.py", line 157, in train
    for i, (input, target) in enumerate(train_loader):
  File "/home/ytan/miniconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 201, in __next__
    return self._process_next_batch(batch)
  File "/home/ytan/miniconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 221, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/home/ytan/miniconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 40, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/ytan/miniconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 109, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/home/ytan/miniconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 109, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/home/ytan/miniconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 89, in default_collate
    storage = batch[0].storage()._new_shared(numel)
  File "/home/ytan/miniconda3/lib/python3.6/site-packages/torch/storage.py", line 113, in _new_shared
    return cls._new_using_fd(size)
RuntimeError: unable to write to file </torch_476_615100490> at /opt/conda/conda-bld/pytorch_1503970438496/work/torch/lib/TH/THAllocator.c:271

Any suggestions?

**Comment by ntuyt** [comment]
IF I set workers = 0, this error will disappear.

**Comment by yjxiong** [comment]
Are you using the latest version of PyTorch?

**Comment by ntuyt** [comment]
Yes, I use the latest version.

________________________________

**Comment by yjxiong** [comment]
You only have one GPU, use `-j 1`. A too high -j number or a too small GPU men size may cause this error.

**Comment by yjxiong** [comment]
And you are using a Batchsize of 128 with only one GPU. I don’t this feasible. It typically needs 4.

**Comment by yjxiong** [comment]
And you are using a Batchsize of 128 with only 1 GPU. I don’t think this is feasible. It typically needs 4 GPUs.

**Comment by ntuyt** [comment]
@yjxiong  Actually I have 4 GPUs, if I set j=1, it will stuck there. Only if j=0 works.

**Comment by yjxiong** [comment]
I have explained why your case failed. Try use 4 GPUs instead.

**Comment by ntuyt** [comment]
I have removed the --gpus option, it will automatically use 4 GPUs. It does not help.

**Comment by yjxiong** [comment]
What is the memory size of your GPUs? If setting -j 4 or lower won’t work, I don’t know what’s the error then. We run this setting on 4 Titan X without problem.

**Comment by ntuyt** [comment]
Memory size is not a problem.

Since I have tested the case when batch size =1.

It will cost very little GPU memory but the problem still exists.


________________________________

**Comment by yjxiong** [comment]
Then I don’t have any instant idea for this. Seeing from the log, it says multiprocessing lib in the dataloaders cannot open/write to some kind of shared momery for communication between processes. It may be a problem in your permission setting or os, which I cannot identify on my side.

**Comment by ntuyt** [comment]
Okay. Thanks for your reply anyway.

I can run your code by setting j=0 anyway.

________________________________

**Comment by yjxiong** [comment]
I don’t think this is a good choice tbh. It wastes too much time for data loading.

I’d rather suggest you either figure out the problem or go with Caffe TSN instead. I don’t want you to blame the code for running super slow at the end of the day.

**Comment by ntuyt** [comment]
Okay. Thanks so much for your advices.


-------- 原始信息 --------
由： yjxiong <notifications@github.com>
日期: 17/10/3 23:48 (GMT+08:00)
收件人： yjxiong/tsn-pytorch <tsn-pytorch@noreply.github.com>
抄送： #YU TAN# <TYU008@e.ntu.edu.sg>, Author <author@noreply.github.com>
主题： Re: [yjxiong/tsn-pytorch] dataloader runtime errors (#17)


I don’t think this is a good choice tbh. It wastes too much time for data loading.

I’d rather suggest you either figure out the problem or go with Caffe TSN instead. I don’t want you to blame the code for running super slow at the end of the day.

―

**Comment by ntuyt** [comment]
I find it is caused by lack of shared memory.
I have increased the shared memory size and it can be trained using 8 workers!

**Comment by yjxiong** [comment]
Good to know. This should lead to reasonable training speed.

**Comment by JiqiangZhou** [comment]
I met the same probles as you. Could you explain carefully how to solve this problem? I have no idea about the "lack of shared memory."
thank you

**Comment by ntuyt** [comment]
@JiqiangZhou Please type in this command "df –k /dev/shm".
You will see the shared memory size in your PC or server.
Then if it is small, you will need to enlarge it.

**Comment by JiqiangZhou** [comment]
@ntuyt available is only 65536, I think it's too small! Iwill try to increase it. Thank you.

**Comment by JiqiangZhou** [comment]
@ntuyt is 2G still too small? It doesn't when I set it to 2G....how much space should I give /dev/shm...

**Comment by JiqiangZhou** [comment]
I tried many times and the space of /dev/shm is at least 35GB.
