### ISSUE TITLE
num_segments when testing

### ISSUE THREAD

**Issue by gss-ucas** [yjxiong/tsn-pytorch#19]
Hi, @yjxiong I saw the following code in test_models.py:

net = TSN(num_class, 1, args.modality,
          base_model=args.arch,
          consensus_type=args.crop_fusion_type,
          dropout=args.dropout)

Does it mean we set num_segmenrts=1 when testing and why??
please help me! Thank you!

**Comment by yjxiong** [comment]
The standard testing of TSN models extracts 25 snippets for each video.

The lines you mentioned are for keeping the output of all snippets. I suggest you read the score evaluation script for how these outputs are used.

**Comment by gss-ucas** [comment]
@yjxiong Thanks for your reply and advice!

**Comment by gwh0112** [comment]
@yjxiong Hi, I see for rgb testing, the number of segments is 25, while for rgbdiff testing, the number automatically changes to 1. Any inside reason for this?
