### ISSUE TITLE
GroupRandomHorizontalFlip return img_group or ret?

### ISSUE THREAD

**Issue by ntuyt** [yjxiong/tsn-pytorch#20]
Hi, I find in the transform.m file.
///////////////////
    def __call__(self, img_group, is_flow=False):
        v = random.random()
        print(v)
        if v < 0.5:
            ret = [img.transpose(Image.FLIP_LEFT_RIGHT) for img in img_group]
            if self.is_flow:
                for i in range(0, len(ret), 2):
                    ret[i] = ImageOps.invert(ret[i])  # invert flow pixel values when flipping
        return img_group
//////////////////

The function return  img_group, should it return ret?

**Comment by yjxiong** [comment]
Thanks. Just fixed.
