### ISSUE TITLE
Runtime Error in RGBDiff Experiment

### ISSUE THREAD

**Issue by dakshvar22** [yjxiong/tsn-pytorch#24]
Hello,

I am running the RGBDiff experiment my own dataset. I am sure the file list is made properly since I have tested them in original TSN repo(Caffe implementation). 
I am using the following command - 
`python main.py sdha-actionness RGBDiff dataset/sdha/train_actionness_rgb.txt dataset/sdha/val_actionness_rgb.txt --arch BNInception --num_segments 7 --gd 40 --lr 0.001 --lr_steps 80 160 --epochs 180 -b 32 -j 8 --dropout 0.8 --snapshot_pref sdha_actionness_bninception_`

I am getting the following error - 

```
Initializing TSN with base model: BNInception.
TSN Configurations:
    input_modality:     RGBDiff
    num_segments:       7
    new_length:         5
    consensus_module:   avg
    dropout_ratio:      0.8

/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py:360: UserWarning: src is not broadcastable to dst, but they have the same number of elements.  Falling back to deprecated pointwise behavior.
  own_state[name].copy_(param)
Converting the ImageNet model to RGB+Diff init model
Traceback (most recent call last):
  File "main.py", line 316, in <module>
    main()
  File "main.py", line 37, in main
    consensus_type=args.consensus_type, dropout=args.dropout, partial_bn=not args.no_partialbn)
  File "/var/www/tsn-pytorch/models.py", line 49, in __init__
    self.base_model = self._construct_diff_model(self.base_model)
  File "/var/www/tsn-pytorch/models.py", line 268, in _construct_diff_model
    new_kernels = params[0].data.mean(dim=1).expand(new_kernel_size).contiguous()
RuntimeError: The expanded size of the tensor (15) must match the existing size (64) at non-singleton dimension 1. at /pytorch/torch/lib/TH/generic/THTensor.c:308
```

Kindly help.

**Comment by dakshvar22** [comment]
Well, turns out it is a pytorch version problem. mean() API changed for newer version and it also expects an additional parameter `keepdim=True`. Added that and it works!

Thanks.

**Comment by yjxiong** [comment]
Thanks for pointing out the issue. This is indeed the case. I have update the SSN codebase (action-detection) to the newer version of PyTorch but forgot to also update tsn-pytorch

**Comment by JiqiangZhou** [comment]
I met the same error and sloved it with the help of ur issue. Thank you dakshvar22 and Xiong!!

**Comment by Robinxin123** [comment]
> Well, turns out it is a pytorch version problem. mean() API changed for newer version and it also expects an additional parameter `keepdim=True`. Added that and it works!
> 
> Thanks.

hello, i am the beginner about pytorch, and i met the same question, can you tell me, where can i add the parameter  keepdim=True.   Many thanks!
