### ISSUE TITLE
Runtime Error 59

### ISSUE THREAD

**Issue by josueortc** [yjxiong/tsn-pytorch#25]
I am trying to run the TSN training with the same specifications of the RGB script in the README.md file. And I end up with this error:

Epoch: [0][0/75], lr: 0.00100	Time 39.106 (39.106)	Data 2.112 (2.112)	Loss 4.6157 (4.6157)	Prec@1 0.781 (0.781)	Prec@5 3.125 (3.125)
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1503965122592/work/torch/lib/THC/generated/../generic/THCTensorSort.cu line=153 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "main.py", line 301, in <module>
    main()
  File "main.py", line 124, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "main.py", line 170, in train
    prec1, prec5 = accuracy(output.data, target, topk=(1,5))
  File "main.py", line 289, in accuracy
    _, pred = output.topk(maxk, 1, True, True)
RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1503965122592/work/torch/lib/THC/generated/../generic/THCTensorSort.cu:153
terminate called without an active exception
Aborted (core dumped)

I was checking the Pytorch guide but there is nothing there about it. I am using Pytorch 0.2, but the code doesn't specify which version to use.

**Comment by josueortc** [comment]
In addition, you should change the path on  /tf_model/bninception/pytorch_load.py from model_zoo/ to tf_model_zoo.

**Comment by yjxiong** [comment]
Haven't  met this error before. It is possibly due to the fast change PyTorch versions. Maybe an older version, say 0.1.2 may help

**Comment by yjxiong** [comment]
`device-side assert triggered`

This looks like a sign of CUDA kernel. I recently came across this error in another project when I mistakenly supplied an NLL loss with ground truth outside the range of prediction, e.g. label 61 with a SoftMax output of 60 classes.
