### ISSUE TITLE
issue about feature extraction

### ISSUE THREAD

**Issue by gss-ucas** [yjxiong/tsn-pytorch#26]
Hi, @yjxiong I want to use your model to extract video feature, my question is following:
1). We should use output of global_average layer as feature, suppose one video has 3 segments, then I can get feature with 3x1024 dimension, no matter rgb modality or flow modality, am I right?
2). Is there any official code to extract feature? 
3). How to choose the number of segments when extracting feature, 3 or 25? 
Thank you in advance!

**Comment by yjxiong** [comment]
1. It depends on how you will use the features. For video features just average over time. For frame features just extraction from each snippet.

2. No. It should be very easy to write it with PyTorch on your own.

3. In testing we use 25 as the standard testing protocol. You are not limited to using this number.
