### ISSUE TITLE
training the RGBDiff model

### ISSUE THREAD

**Issue by cmhungsteve** [yjxiong/tsn-pytorch#28]
I assume we can use the same inputs to train a RGBDiff model. Am I correct?
However, I met this error message:

```
Initializing TSN with base model: resnet101.
TSN Configurations:
    input_modality:     RGBDiff
    num_segments:       5
    new_length:         5
    consensus_module:   avg
    dropout_ratio:      0.8

Converting the ImageNet model to RGB+Diff init model
Traceback (most recent call last):
  File "main.py", line 354, in <module>
    main()
  File "main.py", line 48, in main
    consensus_type=args.consensus_type, dropout=args.dropout, partial_bn=not args.no_partialbn)
  File "/home/tsn-pytorch/models.py", line 49, in __init__
    self.base_model = self._construct_diff_model(self.base_model)
  File "/home/tsn-pytorch/models.py", line 264, in _construct_diff_model
    first_conv_idx = filter(lambda x: isinstance(modules[x], nn.Conv2d), list(range(len(modules))))[0]
TypeError: 'filter' object is not subscriptable
```
Could you help me figure out what it is?
Thank you so much

**Comment by cmhungsteve** [comment]
I think I found the reason. In the newest Python, the output of `filter` is just iterator, so we need to add `list()` out of `filter`.

**Comment by yjxiong** [comment]
This codebase is written in Python 2.7.

**Comment by cmhungsteve** [comment]
I also found that in the newest PyTorch, the dimension will be changed after some calculation like mean, sum, etc. We need to explicitly add `keep_dim=True` in the inputs.

**Comment by yjxiong** [comment]
This TSN repo stands as the first step in our migration from Caffe to PyTorch. So it was written earlier in Python2.7 and PyTorch 0.1.2. I will upgrade it when I got some time.

**Comment by cmhungsteve** [comment]
That would be awesome!! Looking forward to the update.
Thank you.
