### ISSUE TITLE
About the train and test accuracy

### ISSUE THREAD

**Issue by ThinkLock** [yjxiong/tsn-pytorch#30]
Hi yjxiong:
I train and test your TSN model with parameters in README.md.
I got the result as follow:
Model | split1 | split2 | split3
 RGB  | 84.75% | 84.13% | 85.24%
 Flow  | 79.31% | 81.00% | 81.09%
The accuracy of RGB model is similar to your project website [http://yjxiong.me/others/tsn/](url).
But, the accuracy of Flow is very different from yours.
 So, my question is following:

1. Can the pytoch TSN code achieve the offical accuracy in [http://yjxiong.me/others/tsn/](url).
2. Is there anything else to pay attention to when i train the flow model?

Thank you in advance!

**Comment by yjxiong** [comment]
It's verified to reproduce the reported performance. If you encounter problems with optical flow, make sure you are using the correct optical flow algorithm by following the instructions in README.

**Comment by ThinkLock** [comment]
Thank you for your reply. 
I extracted the optical flow images by running your code in project dense_flow.
Now, I achieve the  the reported performance.

**Comment by yjxiong** [comment]
Closing this. Please feel free to reopen it if you meet any further problem.

**Comment by ll490187880** [comment]
@ThinkLock  I also encounter the problem, the accuracy of ucf101 (split 1)  with flow is only 81%， but I used the official code to extract the flow. Can you tell me how to solve the problem? And why do you get 80% in the first time?
