### ISSUE TITLE
Pretrained Models and Performance

### ISSUE THREAD

**Issue by weilheim** [yjxiong/tsn-pytorch#31]
Hi,
I am wondering if there are any pretrained pytorch models that could be downloaded.
In addition, could you pls let us know the performance of this tsn-pytorch on UCF 101 / HMDB 51/ kinetics?
Thanks a lot!

**Comment by utsavgarg** [comment]
Even I trained the models using default settings for split-1 of the UCF-101 dataset and am getting a lower performance than reported. Below are the numbers I got:

RGB - 85.57%
Flow - 84.26%
RGB + Flow - 90.44%

What could be the reason for this?

**Comment by yjxiong** [comment]
This code reproduces the performance of Caffe TSN on UCF101. We haven't tested it on HMDB51.
