### ISSUE TITLE
About the consensus_type

### ISSUE THREAD

**Issue by Koping** [yjxiong/tsn-pytorch#32]
Hi, @yjxiong  

You used the consensus_type of avg in the paper, and l also want to know the effect of the type of topk, however l have not see the code in the program. so could you provide the script about the topk in the forward and backward part?   Or do you have any idea about it?

Thanks for your kindly help!

`class SegmentConsensus(torch.autograd.Function):

    def __init__(self, consensus_type, dim=1):
        self.consensus_type = consensus_type
        self.dim = dim
        self.shape = None

    def forward(self, input_tensor):
        self.shape = input_tensor.size()
        if self.consensus_type == 'avg':
            output = input_tensor.mean(dim=self.dim, keepdim=True)
        elif self.consensus_type == 'identity':
            output = input_tensor
        else:
            output = None

        return output

    def backward(self, grad_output):
        if self.consensus_type == 'avg':
            grad_in = grad_output.expand(self.shape) / float(self.shape[self.dim])
        elif self.consensus_type == 'identity':
            grad_in = grad_output
        else:
            grad_in = None

        return grad_in`

**Comment by yjxiong** [comment]
There is a `torch.topk` function if you want to use the Top-K consensus.
