### ISSUE TITLE
Why the epochs for RGB modality is so high?

### ISSUE THREAD

**Issue by kylemin** [yjxiong/tsn-pytorch#36]
The original paper uses 4500 iterations in total.

**Comment by yjxiong** [comment]
UCF101 has around 6000 videos for training. So one epoch is around 50 iterations. 90 epochs are around 4500 iterations. So it is similar to the paper. Please be aware that the concept of the epoch is defined against videos, not frames.

**Comment by kylemin** [comment]
So that means each batch can have frames from multiple videos?
Like, 1 batch = 3 frames * 128 videos?
