### ISSUE TITLE
worse performance in pytorch

### ISSUE THREAD

**Issue by ZhangLeUestc** [yjxiong/tsn-pytorch#43]
Hi, Thanks for sharing this nice implementation. I notice that the performance of pytorch is somehow worse than the original caffe implementation used in the ECCV paper.  Does anyone know the reason?

**Comment by newpro** [comment]
hey @ZhangLeUestc 
Thanks for your post. Do you mind post your results running this code? I just want to see how worse its getting and do not have good machine on hand. Thx in advance!

**Comment by yjxiong** [comment]
It is verified to produce the same results on UCF101. Let me know if you any question.
