### ISSUE TITLE
Seems to be a typo in transforms.py

### ISSUE THREAD

**Issue by HaoMood** [yjxiong/tsn-pytorch#49]
Hi, thanks for sharing the code.

It seems to be a type in
https://github.com/yjxiong/tsn-pytorch/blob/master/transforms.py#L135
where "875" seems to be ".875".

Thanks.

**Comment by yjxiong** [comment]
Thanks for spotting the issue. Just updated the file and fixed it.

6b51fc28e87d61070b26d7454e5b169042fc851f
