### ISSUE TITLE
TSN followed by RNN

### ISSUE THREAD

**Issue by ZhangLeUestc** [yjxiong/tsn-pytorch#5]
Hi,
Would you plan to release the RNN version of TSN? Like `Long Term Recurrent Convolutioanl Neural Network" by J Donahue ? 
Moreover, why  torch.nn.DataParallel on non-zero GPUs always  raise errors? Is there a smart way to fix this?

Thanks!

**Comment by yjxiong** [comment]
There is no such thing as "RNN version" of TSN in the paper.

To use `DataParallel` on non-zero GPUs, you have to specify the first GPU's ID on every occasion when you use `.cuda()`.
