### ISSUE TITLE
How to reproduce the experiment that combines RGB and optical flow?

### ISSUE THREAD

**Issue by zhouli2025** [yjxiong/tsn-pytorch#50]
Hello, thanks for your code sharing - a great work!

Still, I have a question - we can train models of RGB/RGB-diff/flow modality separately as you introduced in the README.md, but if we want to reproduce the experiment that combines RGB and optical flow, how can we achieve this? Should I write some my own code to jointly infer from two models of RGB and optical flow modality?

Thank you in advance!

**Comment by yjxiong** [comment]
Read the information in the original TSN repo.

https://github.com/yjxiong/temporal-segment-networks

**Comment by kovalepskaia** [comment]
@yjxiong when I run command "make -j" for dense_flow, it displayed error:
dense_flow.cpp:8:27: error: ‘vector’ was not declared in this scope
common.cpp:52:48: error: ‘string’ was not declared in this scope
...
