### ISSUE TITLE
Error in loading weights for BNInception module

### ISSUE THREAD

**Issue by PengZhenghao** [yjxiong/tsn-pytorch#53]
Hi Xiong, Thanks for your great codes.
Trouble happen when I running the `test_model.py` following your instruction:

```
ucf101 RGB data/ucf101_splits kinetics_rgb.pth --arch BNInception --save_scores kinetics_flow_ucf101_scores.txt
```
wherein `kinetics_rgb.pth` comes from [here](https://github.com/shuangshuangguo/caffe2pytorch-tsn) by @shuangshuangguo

The errors look like:

```
RuntimeError: Error(s) in loading state_dict for BNInception:
...
While copying the parameter named "inception_4b_1x1_bn.running_mean", whose dimensions in the model are torch.Size([192]) and whose dimensions in the checkpoint are torch.Size([1, 192]).
...
```

Namely each module has it's weight in checkpoint with one more dimension, compared to what it supposed to be.

I am a beginner with PyTorch. Hope you can answer my question.
Thanks you!

**Comment by PengZhenghao** [comment]
I think maybe this is because that the weight of BNIncepetion module auto-downloaded from your website doesn't fit the model you built.

Maybe because of the PyTorch version (I am using 0.4) or because of the modification of your model which is not reflected on the weight file.

**Comment by gongbudaizhe** [comment]
try pytorch 0.3.1

**Comment by shuangshuangguo** [comment]
@PengZhenghao You can try to modify test_models.py as https://github.com/shuangshuangguo/caffe2pytorch-tsn/blob/master/test_models.py

**Comment by Jenniferlyt** [comment]
hello ,have you solved your problem?  I have met the same error,I have no idea   what i should do next.
thanks a lot!I am looking forward for your early replay.

**Comment by xiadingZ** [comment]
Can anyone give a hint how to transfer the bninception to pytorch1.0 model? I want to train this code under pytorch 1.0

**Comment by dfxue** [comment]
> You can see [pretrainedmodels](https://github.com/Cadene/pretrained-models.pytorch), it has pretrained bninception. I have succeed to run tsn-pytorch using pytorch1.0 with it.

hello, I am running tsn-pytorch using pytorch1.1, and get the issue of size mismatch. Could you share your code about this problem. Thanks.
