### ISSUE TITLE
Test error

### ISSUE THREAD

**Issue by KenyonZhao233** [yjxiong/tsn-pytorch#55]
When I test the model, I get a error(list index out of range)

python test_models.py ucf101 RGB <ucf101_rgb_val_list> ucf101_bninception_rgb_checkpoint.pth \
   --arch BNInception --save_scores <score_file_name>

Traceback (most recent call last):
  File "test_models.py", line 128, in <module>
    rst = eval_video((i, data, label))
  File "test_models.py", line 116, in eval_video
    rst = net(input_var).data.cpu().numpy().copy()
........
IndexError: list index out of range

**Comment by Mohamad73** [comment]
Hello, I am getting the same problem, did you figure out the solution?

**Comment by lacasanostra12** [comment]
Hi, I also would like to know how you managed to solve the issue ? I believe this is about the .txt file as input but I am not sure in what kind of format should I put it in and what to include.

**Comment by KenyonZhao233** [comment]
When you make the score file, something goes wrong. Check your score file and you may find an error. Some values are empty.

**Comment by KenyonZhao233** [comment]
@[https://github.com/yjxiong/tsn-pytorch/issues/55#issuecomment-414293289](url)When you make the score file, something goes wrong. Check your score file and you may find an error. Some values are empty.

**Comment by Mohamad73** [comment]
What do you mean by creating the score file?
