### ISSUE TITLE
Getting Very low accuracy ( 38%) with HMDB-51

### ISSUE THREAD

**Issue by Mohamad73** [yjxiong/tsn-pytorch#63]
I am getting around 38% with RGB modality on the HMDB-51. I am running it as shown below. Am I doing anything wrong?
`python main.py hmdb51 RGB hmdb51_rgb_train_list hmdb51_rgb_val_list --arch BNInception --num_segments 3 --gd 20 --lr 0.001 --lr_steps 30 60 --epochs 80 --b 100 -j 2 --dropout 0.8`

**Comment by yjxiong** [comment]
HMDB needs more epochs. Please calculate the parameters based on the caffe TSN repo's solver files.

**Comment by Mohamad73** [comment]
First of all thank you for your replies Even when I run it on 160 epochs, it gives me the same result. I have only two gpus. I read that in Caffe the effective batchsize equals to batch_size*iter_size*n_gpu has to be 128.
How do I accommodate for that in pytorch since I dont have access to iter_size!

**Comment by Mkarami3** [comment]
Hi Mohamad73,
Did you find the solution to your question? Kindly can you please share it with me?
Thank you
