### ISSUE TITLE
Getting 70.5% on split 1

### ISSUE THREAD

**Issue by Chonwing** [yjxiong/tsn-pytorch#66]
Is it normal that I am getting this high accuracy ON HMDB-51 Dataset

**Comment by yjxiong** [comment]
I think it is correct if you are using two streams. Please refer to the journal version of TSN for the results

https://arxiv.org/pdf/1705.02953.pdf

**Comment by Chonwing** [comment]
How come people that cite you say that your accuracy is 68.5

**Comment by tiangarin** [comment]
hi, can I ask how to get so high performance? can you tell me your setting? thanks.
