### ISSUE TITLE
What's the difference between model.load_state_dict() & model.base_model.load_state_dict() ?

### ISSUE THREAD

**Issue by k89231** [yjxiong/tsn-pytorch#68]
It seems that when training, the `base_model` is used to forwarding data. When calling `args.resume`, how does the resumed pretrained model affect the `base_model` ?

**Comment by yjxiong** [comment]
`base_model` is a submodule of `TSN`. You can consult the PyTorch documentation on how the loading is done. Overall, a module recursively loads all its submodules' parameters.
