### ISSUE TITLE
when i build the dense_flow ,the followed

### ISSUE THREAD

**Issue by lingtengqiu** [yjxiong/tsn-pytorch#69]
-- Configuring incomplete, errors occurred!
See also "/media/nolib/7cff3dfa-1db7-498a-a8a2-edf8a34bd36c/XXX/temporal-segment-network-pytorch/3rd-party/opencv-2.4.13/build/CMakeFiles/CMakeOutput.log".
See also "/media/nolib/7cff3dfa-1db7-498a-a8a2-edf8a34bd36c/XXX/temporal-segment-network-pytorch/3rd-party/opencv-2.4.13/build/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.
Failed to build OpenCV. Please check the logs above.

**Comment by yjxiong** [comment]
`Configuring incomplete, errors occurred!` Seems some libraries are missing on your machine. Go through your log to see what happened.
