### ISSUE TITLE
size mismatch

### ISSUE THREAD

**Issue by zhangtao22** [yjxiong/tsn-pytorch#74]
.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for BNInception:
        size mismatch for conv1_7x7_s2_bn.running_var: copying a param with shape torch.Size([1, 64]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for conv1_7x7_s2_bn.bias: copying a param with shape torch.Size([1, 64]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for conv1_7x7_s2_bn.weight: copying a param with shape torch.Size([1, 64]) from checkpoint, the shape in current model is torch.Size([64]).
...

**Comment by OhYoungTack** [comment]
@zhangtao22 

I have the same experience. How did you solve it?

**Comment by ccmeteorljh** [comment]
i have same error, can you tell me how to fix it? thanks @zhangtao22

**Comment by Phylake1337** [comment]
@ccmeteorljh @OhYoungTack @zhangtao22  
I found that link elsewhere ya could check it guys GL
https://github.com/Cadene/pretrained-models.pytorch/issues/70#issuecomment-410479575

**Comment by AiMizuno** [comment]
I have the same experience too. @zhangtao22

**Comment by Ixiaohuihuihui** [comment]
I met the same error while the pytorch version is 0.4.1.
Then I changed the pytorch version to 0.3.1. The error can be solved.

**Comment by AiMizuno** [comment]
> I met the same error while the pytorch version is 0.4.1.
> Then I changed the pytorch version to 0.3.1. The error can be solved.

You are right. Thanks

**Comment by yangyuke001** [comment]
@OhYoungTack  @ccmeteorljh  @AiMizuno 
I met the same error,and my pytorch version is 1.1.0,
first,download bn_inception-9f5701afb96c8044_fixed.pth to /home/model/path/
second,changed the tf_model_zoo/BNInception/pytorch_load.py:

add lines:
weight_path = '/home/model/path/pretrained_model/bn_inception-9f5701afb96c8044.pth'
weight_fixed_path = '/home/model/path/pretrained_model/bn_inception-9f5701afb96c8044_fixed.pth'
state_dict = torch.load(weight_path)
for name, weights in state_dict.items():
   if 'bn' in name :
       state_dict[name] = weights.squeeze(0)
torch.save(state_dict,weight_fixed_path)

change lines:
class BNInception(nn.Module):
    def __init__(self, model_path='tf_model_zoo/bninception/bn_inception.yaml', num_classes=101,
                        weight_url = weight_fixed_path):
                    #weight_url='https://yjxiong.blob.core.windows.net/models/bn_inception-9f5701afb96c8044.pth'):
       ...
        self.load_state_dict(torch.load(weight_url))
      #self.load_state_dict(torch.utils.model_zoo.load_url(weight_url))

**Comment by Raazzta** [comment]
> @OhYoungTack @ccmeteorljh @AiMizuno
> I met the same error,and my pytorch version is 1.1.0,
> first,download bn_inception-9f5701afb96c8044_fixed.pth to /home/model/path/
> second,changed the tf_model_zoo/BNInception/pytorch_load.py:
> 
> add lines:
> weight_path = '/home/model/path/pretrained_model/bn_inception-9f5701afb96c8044.pth'
> weight_fixed_path = '/home/model/path/pretrained_model/bn_inception-9f5701afb96c8044_fixed.pth'
> state_dict = torch.load(weight_path)
> for name, weights in state_dict.items():
> if 'bn' in name :
> state_dict[name] = weights.squeeze(0)
> torch.save(state_dict,weight_fixed_path)
> 
> change lines:
> class BNInception(nn.Module):
> def **init**(self, model_path='tf_model_zoo/bninception/bn_inception.yaml', num_classes=101,
> weight_url = weight_fixed_path):
> #weight_url='https://yjxiong.blob.core.windows.net/models/bn_inception-9f5701afb96c8044.pth'):
> ...
> self.load_state_dict(torch.load(weight_url))
> #self.load_state_dict(torch.utils.model_zoo.load_url(weight_url))

Hi @yangyuke001 , where can I donwload **bn_inception-9f5701afb96c8044_fixed.pth**? Thx

**Comment by yhc1994** [comment]
> > @OhYoungTack @ccmeteorljh @AiMizuno
> > I met the same error,and my pytorch version is 1.1.0,
> > first,download bn_inception-9f5701afb96c8044_fixed.pth to /home/model/path/
> > second,changed the tf_model_zoo/BNInception/pytorch_load.py:
> > add lines:
> > weight_path = '/home/model/path/pretrained_model/bn_inception-9f5701afb96c8044.pth'
> > weight_fixed_path = '/home/model/path/pretrained_model/bn_inception-9f5701afb96c8044_fixed.pth'
> > state_dict = torch.load(weight_path)
> > for name, weights in state_dict.items():
> > if 'bn' in name :
> > state_dict[name] = weights.squeeze(0)
> > torch.save(state_dict,weight_fixed_path)
> > change lines:
> > class BNInception(nn.Module):
> > def **init**(self, model_path='tf_model_zoo/bninception/bn_inception.yaml', num_classes=101,
> > weight_url = weight_fixed_path):
> > #weight_url='https://yjxiong.blob.core.windows.net/models/bn_inception-9f5701afb96c8044.pth'):
> > ...
> > self.load_state_dict(torch.load(weight_url))
> > #self.load_state_dict(torch.utils.model_zoo.load_url(weight_url))
> 
> Hi @yangyuke001 , where can I donwload **bn_inception-9f5701afb96c8044_fixed.pth**? Thx

https://yjxiong.blob.core.windows.net/models/bn_inception-9f5701afb96c8044.pth

**Comment by Raazzta** [comment]
> > > @OhYoungTack @ccmeteorljh @AiMizuno
> > > I met the same error,and my pytorch version is 1.1.0,
> > > first,download bn_inception-9f5701afb96c8044_fixed.pth to /home/model/path/
> > > second,changed the tf_model_zoo/BNInception/pytorch_load.py:
> > > add lines:
> > > weight_path = '/home/model/path/pretrained_model/bn_inception-9f5701afb96c8044.pth'
> > > weight_fixed_path = '/home/model/path/pretrained_model/bn_inception-9f5701afb96c8044_fixed.pth'
> > > state_dict = torch.load(weight_path)
> > > for name, weights in state_dict.items():
> > > if 'bn' in name :
> > > state_dict[name] = weights.squeeze(0)
> > > torch.save(state_dict,weight_fixed_path)
> > > change lines:
> > > class BNInception(nn.Module):
> > > def **init**(self, model_path='tf_model_zoo/bninception/bn_inception.yaml', num_classes=101,
> > > weight_url = weight_fixed_path):
> > > #weight_url='https://yjxiong.blob.core.windows.net/models/bn_inception-9f5701afb96c8044.pth'):
> > > ...
> > > self.load_state_dict(torch.load(weight_url))
> > > #self.load_state_dict(torch.utils.model_zoo.load_url(weight_url))
> > 
> > 
> > Hi @yangyuke001 , where can I donwload **bn_inception-9f5701afb96c8044_fixed.pth**? Thx
> 
> https://yjxiong.blob.core.windows.net/models/bn_inception-9f5701afb96c8044.pth

Thank you for your reply @yhc1994, but I need to use **bn_inception-9f5701afb96c8044_fixed.pth** (note that suffix "_fixed").

**Comment by yhc1994** [comment]
> > > > @OhYoungTack @ccmeteorljh @AiMizuno
> > > > I met the same error,and my pytorch version is 1.1.0,
> > > > first,download bn_inception-9f5701afb96c8044_fixed.pth to /home/model/path/
> > > > second,changed the tf_model_zoo/BNInception/pytorch_load.py:
> > > > add lines:
> > > > weight_path = '/home/model/path/pretrained_model/bn_inception-9f5701afb96c8044.pth'
> > > > weight_fixed_path = '/home/model/path/pretrained_model/bn_inception-9f5701afb96c8044_fixed.pth'
> > > > state_dict = torch.load(weight_path)
> > > > for name, weights in state_dict.items():
> > > > if 'bn' in name :
> > > > state_dict[name] = weights.squeeze(0)
> > > > torch.save(state_dict,weight_fixed_path)
> > > > change lines:
> > > > class BNInception(nn.Module):
> > > > def **init**(self, model_path='tf_model_zoo/bninception/bn_inception.yaml', num_classes=101,
> > > > weight_url = weight_fixed_path):
> > > > #weight_url='https://yjxiong.blob.core.windows.net/models/bn_inception-9f5701afb96c8044.pth'):
> > > > ...
> > > > self.load_state_dict(torch.load(weight_url))
> > > > #self.load_state_dict(torch.utils.model_zoo.load_url(weight_url))
> > > 
> > > 
> > > Hi @yangyuke001 , where can I donwload **bn_inception-9f5701afb96c8044_fixed.pth**? Thx
> > 
> > 
> > https://yjxiong.blob.core.windows.net/models/bn_inception-9f5701afb96c8044.pth
> 
> Thank you for your reply @yhc1994, but I need to use **bn_inception-9f5701afb96c8044_fixed.pth** (note that suffix "_fixed").

the _fixed version would be generated automatically after you run the code above, that is how yuke's code works.

**Comment by Raazzta** [comment]
Hi @yhc1994 ,
How can I run the code if I could not run it? Also, @yangyuke001 mentioned that the file need to be **download** first then run the code. In addition, that file is not generated in the code above. Anyway, do you have _fixed version?
