### ISSUE TITLE
Inverting flow values while flipping 

### ISSUE THREAD

**Issue by utsavgarg** [yjxiong/tsn-pytorch#8]
Why do you invert the values for optical flow when the image is flipped ? Done in line 57 and 121 in `transforms.py`

**Comment by yjxiong** [comment]
Cause optical flow is a vector field.

**Comment by bityangke** [comment]
Hi，Yuanjun
Will there be a big difference in performance if I did not do the invert op(simply treating the optical flow as image)?
Thanks

**Comment by yjxiong** [comment]
Not very much difference. Just to make the operation technically sound.
