### ISSUE TITLE
How to do modality fusion

### ISSUE THREAD

**Issue by yojayc** [yjxiong/tsn-pytorch#89]
Anyone knows how to implement modality fusion to get fusion result of rgb stream and flow stream in the pytorch version of tsn?

**Comment by Robinxin123** [comment]
hello, i have the same question, do you solve it ? thanks

**Comment by yojayc** [comment]
> hello, i have the same question, do you solve it ? thanks

I use the Video-level testing part of the original version of TSN to calculate the final results.
[](https://github.com/yjxiong/temporal-segment-networks)

**Comment by Robinxin123** [comment]
ah, thanks, i got the same solution in another issue.

**Comment by yjxiong** [comment]
Yes. You can use the Caffe TSN's Python scripts for modaity fusion tests. 

This is an experimental project. We have released a full fledged toolbox for Pytorch at [MMAction](https://github.com/open-mmlab/mmaction).
